# Generated by Django 4.2.20 on 2026-02-19 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ELW', '0002_remove_logininfo'),
        ('Account', '0003_migrate_logininfo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIScoreRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_accuracy', models.IntegerField(default=0, help_text='是否正确回答了问题核心要点 (0-100分)', verbose_name='内容准确性')),
                ('language_expression', models.IntegerField(default=0, help_text='语法正确性、词汇使用 (0-100分)', verbose_name='语言表达')),
                ('completeness', models.IntegerField(default=0, help_text='是否完整回答了问题 (0-100分)', verbose_name='完整性')),
                ('logical_coherence', models.IntegerField(default=0, help_text='表达是否清晰、有条理 (0-100分)', verbose_name='逻辑连贯性')),
                ('total_score', models.FloatField(default=0.0, help_text='加权计算的总分 (0-100分)', verbose_name='总分')),
                ('feedback', models.TextField(help_text='AI生成的整体反馈 (2-3句话)', verbose_name='整体反馈')),
                ('suggestions', models.JSONField(default=list, help_text='具体的改进建议列表', verbose_name='改进建议')),
                ('grammar_errors', models.JSONField(default=list, help_text='语法错误列表 [{"error": "错误类型", "correction": "修改建议", "location": "位置"}]', verbose_name='语法错误')),
                ('vocabulary_suggestions', models.JSONField(default=list, help_text='词汇提升建议列表 [{"word": "原词", "better": "更好的词", "reason": "原因"}]', verbose_name='词汇建议')),
                ('student_answer', models.TextField(help_text='学生的原始答案', verbose_name='学生答案')),
                ('score_time', models.DateTimeField(auto_now=True, verbose_name='评分时间')),
                ('ai_model', models.CharField(choices=[('VolcEngine', '火山引擎'), ('ZhipuAI', '智谱清言'), ('Local', '本地模型')], default='VolcEngine', max_length=50, verbose_name='AI模型')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_score_records', to='Account.students', verbose_name='学生')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_scores', to='ELW.subquestion', verbose_name='题目')),
            ],
            options={
                'verbose_name': 'AI评分记录',
                'verbose_name_plural': 'AI评分记录',
                'db_table': 'ai_score_record',
                'ordering': ['-score_time'],
                'indexes': [models.Index(fields=['student'], name='ai_score_re_student_8d079a_idx'), models.Index(fields=['sub_question'], name='ai_score_re_sub_que_cafbd9_idx'), models.Index(fields=['score_time'], name='ai_score_re_score_t_c6b29f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIExplanationRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_answer_explanation', models.TextField(help_text='详细解释为什么这个答案是正确的，引用听力原文', verbose_name='正确答案解释')),
                ('distractor_analysis', models.JSONField(default=list, help_text='干扰项错误原因列表 [{"option": "A", "reason": "为什么这个选项是错误的"}]', verbose_name='干扰项分析')),
                ('key_points', models.JSONField(default=list, help_text='听力材料中的关键点列表', verbose_name='关键点')),
                ('listening_tips', models.TextField(help_text='针对这类题目的听力技巧建议', verbose_name='听力技巧')),
                ('related_knowledge', models.TextField(blank=True, help_text='相关的语言知识点（语法/词汇）', null=True, verbose_name='相关知识')),
                ('generate_time', models.DateTimeField(auto_now=True, verbose_name='生成时间')),
                ('ai_model', models.CharField(choices=[('VolcEngine', '火山引擎'), ('ZhipuAI', '智谱清言'), ('Local', '本地模型')], default='VolcEngine', max_length=50, verbose_name='AI模型')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_explanations', to='ELW.subquestion', verbose_name='题目')),
            ],
            options={
                'verbose_name': 'AI解释记录',
                'verbose_name_plural': 'AI解释记录',
                'db_table': 'ai_explanation_record',
                'ordering': ['-generate_time'],
                'indexes': [models.Index(fields=['sub_question'], name='ai_explanat_sub_que_7997d3_idx'), models.Index(fields=['generate_time'], name='ai_explanat_generat_ea6e07_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIConversationHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手'), ('system', '系统')], default='user', max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('context', models.JSONField(default=dict, help_text='对话上下文信息 {"practice_id": 1, "page_id": 2, "sub_question_id": 3}', verbose_name='上下文')),
                ('message_time', models.DateTimeField(auto_now_add=True, verbose_name='消息时间')),
                ('ai_model', models.CharField(choices=[('VolcEngine', '火山引擎'), ('ZhipuAI', '智谱清言'), ('Local', '本地模型')], default='VolcEngine', max_length=50, verbose_name='AI模型')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='Account.students', verbose_name='学生')),
            ],
            options={
                'verbose_name': 'AI对话历史',
                'verbose_name_plural': 'AI对话历史',
                'db_table': 'ai_conversation_history',
                'ordering': ['message_time'],
                'indexes': [models.Index(fields=['student'], name='ai_conversa_student_859507_idx'), models.Index(fields=['message_time'], name='ai_conversa_message_fd6538_idx'), models.Index(fields=['role'], name='ai_conversa_role_4cc5dc_idx')],
            },
        ),
    ]
