# Generated by Django 4.2.16 on 2025-04-24 22:23

import ELW.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('Query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_url', models.FileField(upload_to=ELW.models.documents_upload_to, verbose_name='文件')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('week', models.IntegerField(default=0)),
                ('action', models.CharField(max_length=20)),
                ('action_time', models.DateTimeField()),
                ('last_active_time', models.CharField(max_length=50)),
                ('device_info', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MainQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('choice', '选择题'), ('matching', '连线题'), ('correction', '改错题'), ('comprehension', '主观题'), ('text', '纯文本')], default='choice', max_length=20, verbose_name='题目类型')),
                ('question_text', models.TextField(verbose_name='大题题干')),
                ('image_url', models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='大题图片')),
                ('maximum_play', models.IntegerField(default=3)),
                ('minimum_play', models.IntegerField(default=0)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('allow_pause', models.BooleanField(blank=True, default=False, null=True)),
                ('limited_time', models.TimeField(blank=True, null=True)),
                ('no_media', models.BooleanField(blank=True, default=False, null=True, verbose_name='不需要视频文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='MediaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('theme', models.CharField(default='', max_length=50)),
                ('abstract', models.TextField(default='')),
                ('keywords', models.TextField(default='')),
                ('transcript', models.TextField(default='')),
                ('media_url', models.CharField(max_length=100)),
                ('image_url', models.CharField(default='', max_length=10000)),
            ],
            options={
                'verbose_name_plural': '题库管理',
            },
        ),
        migrations.CreateModel(
            name='PageMainQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_main_questions', to='ELW.mainquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='单元序号')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='单元名称')),
                ('type', models.CharField(choices=[('practice', '练习'), ('exam', '考试'), ('task', ' 作业'), ('quiz', '小测')], default='practice', max_length=20, verbose_name='题目类型')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='Account.class')),
                ('overdue_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='Query.overduedeductionrule')),
            ],
            options={
                'verbose_name_plural': '试卷管理',
            },
        ),
        migrations.CreateModel(
            name='TimeManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=0, verbose_name='开放周次')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='考试日期')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='时长限制，单位分钟')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_management', to='ELW.unit')),
            ],
        ),
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='小题内容')),
                ('image_url', models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='图片')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='提示')),
                ('answer', models.TextField(default='test', verbose_name='参考答案')),
                ('analysis', models.TextField(blank=True, null=True, verbose_name='解析')),
                ('score', models.FloatField(default=1.0, verbose_name='分数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('main_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='ELW.mainquestion')),
            ],
        ),
        migrations.CreateModel(
            name='PaperPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='页面顺序')),
                ('text', models.TextField(blank=True, null=True, verbose_name='页面文本')),
                ('limited_time', models.IntegerField(blank=True, default=0, null=True, verbose_name='时长限制，单位分钟')),
                ('can_modify', models.BooleanField(blank=True, default=True, null=True, verbose_name='允许修改答案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_pages', to='ELW.unit')),
            ],
        ),
        migrations.CreateModel(
            name='PageSubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_main_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_sub_questions', to='ELW.pagemainquestion')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_sub_questions', to='ELW.subquestion')),
            ],
        ),
        migrations.AddField(
            model_name='pagemainquestion',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_main_questions', to='ELW.paperpage'),
        ),
        migrations.CreateModel(
            name='MatchingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(max_length=1, verbose_name='选项字母')),
                ('option_content', models.TextField(blank=True, null=True, verbose_name='选项内容')),
                ('image_url', models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='选项图片')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchingOptions', to='ELW.subquestion')),
            ],
        ),
        migrations.AddField(
            model_name='mainquestion',
            name='media_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_questions', to='ELW.mediamaterial'),
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('insert', '插入'), ('delete', '删除'), ('revise', '修改')], default='insert', max_length=10, verbose_name='改错类型')),
                ('index', models.IntegerField(default=0, verbose_name='修改位置')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='ELW.subquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(max_length=1, verbose_name='选项字母')),
                ('option_content', models.TextField(blank=True, null=True, verbose_name='选项内容')),
                ('image_url', models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='选项图片')),
                ('is_answer', models.BooleanField(default=False, verbose_name='是否为答案')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ELW.subquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, verbose_name='填空位置')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanks', to='ELW.subquestion')),
            ],
        ),
    ]
