# Generated by Django 4.2.16 on 2024-12-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELW', '0004_alter_logininfo_device_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='device_info',
            field=models.CharField(max_length=500),
        ),
    ]
