# Generated by Django 4.2.16 on 2024-12-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ELW', '0005_alter_logininfo_device_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='last_action_time',
            field=models.CharField(max_length=50),
        ),
    ]
