# Generated by Django 4.2.16 on 2024-12-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ELW', '0006_alter_logininfo_last_action_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logininfo',
            old_name='last_action_time',
            new_name='last_active_time',
        ),
    ]
