# Generated by Django 4.2.20 on 2026-03-16 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0003_migrate_logininfo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBehaviorWeeklyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='统计周期开始（周一）')),
                ('period_end', models.DateField(verbose_name='统计周期结束（周日）')),
                ('S_A', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='正确率与用时维度')),
                ('S_B', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='出勤与投入维度')),
                ('S_C', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='专注与用时偏差维度')),
                ('S_D', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='提示使用维度')),
                ('F_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='综合形成性评分')),
                ('P_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='参与度分')),
                ('growth_bonus', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='成长奖励分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_weekly_scores', to='Account.students', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生周度行为评分',
                'verbose_name_plural': '学生周度行为评分',
                'db_table': 'student_behavior_score',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['student'], name='student_beh_student_50a606_idx'), models.Index(fields=['period_start'], name='student_beh_period__6577cf_idx'), models.Index(fields=['F_score'], name='student_beh_F_score_c395e8_idx')],
                'unique_together': {('student', 'period_start')},
            },
        ),
    ]
