"""
Django settings for English_Listening_Website project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
import os
import mimetypes
import ELW.apps
import pymysql
pymysql.install_as_MySQLdb()

# 尝试导入 decouple，如果没有安装则使用 os.environ
try:
    from decouple import config
except ImportError:
    # 如果没有安装 decouple，使用 os.environ 作为后备
    def config(key, default=None):
        return os.environ.get(key, default)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure correct MIME types for static files on Windows (avoid application/x-css)
mimetypes.add_type('text/css', '.css', strict=True)
mimetypes.add_type('application/javascript', '.js', strict=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-k1ofy%53p55+ghbswfn(6c6jjcihx_7#q4e#d7gt&$5)cn$cau')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default='True') == 'True'

ALLOWED_HOSTS = []


# Application definition

#需要配置
# pip install pymysql, django-simpleui, daphne, channels, django-filter, openpyxl, python-docx, requests, apscheduler,
# pip install channels channels_redis

INSTALLED_APPS = [
    'simpleui',
    "daphne",
    'channels',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django_filters',
    # Django REST Framework
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # Token blacklist for logout
    'corsheaders',
    'drf_spectacular',  # OpenAPI 3.0 schema generation
    # Common services module (must be before other apps that use it)
    'common.apps.CommonConfig',
    # 注册app'ELW'
    'ELW.apps.ElwConfig',
    "forum",
    "announce",
    "accessment",
    'student_ELW',
    'stu_practice',
    'Account.apps.AccountConfig',
    'Backup.apps.BackupConfig',
    'Log.apps.LogConfig',
    'Query.apps.QueryConfig',
    'AI_module',  # AI评分和对话模块
]
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
ASGI_APPLICATION= 'English_Listening_Website.asgi.application'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'English_Listening_Website.middleware.SessionTimeoutMiddleware',
    'English_Listening_Website.middleware.StaticFileContentTypeMiddleware',  # 确保静态文件Content-Type正确
    'Log.middleware.CurrentUserMiddleware',  # Log应用获取当前登录用户的中间件
]

ROOT_URLCONF = 'English_Listening_Website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': []
        # 'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'English_Listening_Website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='day0425'),
        'USER': config('DB_USER', default='root'),
        'PASSWORD': config('DB_PASSWORD', default='123456'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

# 不激活Django的时区支持,即没有时区信息的日期时间
# USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 【用于测试，后续应转为连接数据库】
MEDIA_URL = '/media_material/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_material')

# 设置会话过期时间（单位：秒）
SESSION_COOKIE_AGE = 60 * 30  # 30分钟
# 用户登录后，浏览器关闭时，关闭登录状态
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


SIMPLEUI_HOME_INFO=False
SIMPLEUI_ANALYSIS=False
SIMPLEUI_INDEX = 'http://localhost:8000/login'

# ============================================
# Django REST Framework Configuration
# ============================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Keep for backward compatibility
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'EXCEPTION_HANDLER': 'common.api.exceptions.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ============================================
# JWT Configuration
# ============================================

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # Access token 有效期：1小时
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Refresh token 有效期：7天
    'ROTATE_REFRESH_TOKENS': True,  # 刷新时生成新的 refresh token
    'BLACKLIST_AFTER_ROTATION': True,  # 刷新后将旧 token 加入黑名单
    'UPDATE_LAST_LOGIN': True,  # 更新最后登录时间
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
}

# ============================================
# CORS Configuration
# ============================================

# CORS settings for frontend-backend separation
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React development server
    "http://localhost:5173",  # Vite development server
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
]

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Allowed HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allowed headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# For development only - allow all origins (remove in production)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

# ============================================
# drf-spectacular Configuration (OpenAPI 3.0)
# ============================================

SPECTACULAR_SETTINGS = {
    'TITLE': 'AI辅助听力学习平台 API',
    'DESCRIPTION': 'AI辅助听力学习平台后端接口文档，基于Django REST Framework开发',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,  # 分离请求和响应schema
    'SCHEMA_PATH_PREFIX': '/api/v1',  # API路径前缀
    'TAGS': [
        {'name': '认证', 'description': '用户认证相关接口'},
        {'name': '用户管理', 'description': '用户、学生、教师、班级管理接口'},
        {'name': '内容管理', 'description': '媒体素材、单元、页面、题目管理接口'},
        {'name': '论坛', 'description': '论坛帖子、评论相关接口'},
        {'name': '公告', 'description': '公告、消息相关接口'},
        {'name': '考试', 'description': '考试、练习相关接口'},
        {'name': '数据查询', 'description': '考勤、学习记录、统计查询接口'},
    ],
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
            'description': 'JWT Token认证，格式：Bearer <token>',
        }
    },
    'AUTHENTICATION_WHITELIST': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}
