# Generated by Django 4.2.16 on 2025-04-24 22:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('ELW', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('integrity_score', models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='诚信分')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='总分')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELW.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.students')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('remaining_time', models.FloatField(blank=True, default=0, null=True)),
                ('late_score', models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='逾期扣分')),
                ('page_score', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='页面原始分')),
                ('feedback', models.TextField(blank=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='ELW.paperpage')),
                ('student_exam_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_records', to='accessment.studentexamrecord')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='答案文本')),
                ('index', models.IntegerField(blank=True, null=True, verbose_name='索引')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='改错类型')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='小题得分')),
                ('student_page_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accessment.studentpagerecord')),
                ('sub_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ELW.subquestion')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMediaPlayRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_count', models.IntegerField(default=0)),
                ('last_pause_time', models.FloatField(default=0)),
                ('main_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELW.mainquestion')),
                ('media_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ELW.mediamaterial')),
                ('student_exam_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accessment.studentexamrecord')),
            ],
            options={
                'unique_together': {('student_exam_record', 'main_question', 'media_material')},
            },
        ),
    ]
