# Generated by Django 4.2.20 on 2025-04-23 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('ELW', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPracticeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='总分')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELW.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.students')),
            ],
        ),
    ]
