# Generated by Django 4.2.20 on 2025-04-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessment', '0001_initial'),
        ('stu_practice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentPracticeRecord',
        ),
    ]
