# Generated by Django 4.2.20 on 2025-04-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpracticerecord',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='总分'),
        ),
    ]
