# Generated by Django 4.2.20 on 2025-04-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_practice', '0003_studentpagerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentPageRecord',
        ),
    ]
