# Generated by Django 4.2.20 on 2025-04-04 11:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ELW', '0001_initial'),
        ('stu_practice', '0004_delete_studentpagerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('remaining_time', models.FloatField(default=0)),
                ('integrity_score', models.DecimalField(decimal_places=1, default=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='诚信分')),
                ('page_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='页面总分')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_practice_student_records', to='ELW.paperpage')),
                ('student_practice_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_practice_page_records', to='stu_practice.studentpracticerecord')),
            ],
        ),
    ]
