# Generated by Django 4.2.20 on 2025-04-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_practice', '0005_studentpagerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpagerecord',
            name='page_score',
        ),
        migrations.AlterField(
            model_name='studentpagerecord',
            name='student_practice_record',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='页面总分'),
        ),
    ]
