# Generated by Django 4.2.20 on 2025-04-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_practice', '0006_remove_studentpagerecord_page_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentPageRecord',
        ),
    ]
