# Generated by Django 4.2.16 on 2025-04-24 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_rows', models.IntegerField(blank=True, null=True)),
                ('seat_cols', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OverdueDeductionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, unique=True, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, verbose_name='规则描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认规则')),
            ],
            options={
                'verbose_name': '逾期扣分规则',
                'verbose_name_plural': '逾期扣分规则',
            },
        ),
        migrations.CreateModel(
            name='OverduePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=50, verbose_name='时间段名称')),
                ('min_days', models.IntegerField(verbose_name='最小天数')),
                ('max_days', models.IntegerField(blank=True, null=True, verbose_name='最大天数')),
                ('deduction_rate', models.DecimalField(decimal_places=2, help_text='例如0.9表示扣10%，剩余90%', max_digits=3, verbose_name='扣分比例')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='Query.overduedeductionrule')),
            ],
            options={
                'verbose_name': '逾期时间段',
                'verbose_name_plural': '逾期时间段',
                'ordering': ['min_days'],
            },
        ),
        migrations.AddConstraint(
            model_name='overduedeductionrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_rule'),
        ),
        migrations.AddField(
            model_name='classroomlayout',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.class'),
        ),
    ]
