# Generated by Django 4.2.16 on 2025-04-24 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=64, verbose_name='公告标题')),
                ('a_content', models.CharField(max_length=3000, null=True, verbose_name='公告内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布日期')),
                ('receivers', models.ManyToManyField(blank=True, related_name='announcements', to='Account.students')),
                ('teachers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='Account.teachers')),
            ],
            options={
                'verbose_name_plural': '公告管理',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_announcement', models.BooleanField(default=False)),
                ('announcement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='announce.announcement')),
                ('post', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forum.post')),
            ],
        ),
    ]
