# Generated by Django 4.2.16 on 2025-04-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(choices=[('backup', 'Backup'), ('restore', 'Restore')], max_length=10)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('backup_to', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '数据库备份',
            },
        ),
    ]
